=== ifeghali/php-src/scripts/ext_skel_ng/extension.dtd
<!ELEMENT extension (name|summary|description|license|maintainers|logo|release|changelog|functions|constants|globals|deps|resources|code|streams|tests)*>

<!ELEMENT name (#PCDATA)>

<!ELEMENT summary (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT maintainers (maintainer)+>

<!ELEMENT maintainer (user|role|name|email)*>

<!ELEMENT logo (#PCDATA)>
<!ATTLIST logo
  src CDATA #REQUIRED
>

<!ELEMENT user (#PCDATA)>

<!ELEMENT role (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT changelog (release)*>

<!ELEMENT release (version|license|state|date|notes|filelist|deps)*>

<!ELEMENT version (#PCDATA)>

<!ELEMENT state (#PCDATA)>

<!ELEMENT license (#PCDATA)>

<!ELEMENT date (#PCDATA)>

<!ELEMENT notes (#PCDATA)>

<!ELEMENT functions (function)*>
<!ELEMENT function (summary|proto|description|code)*>
<!ATTLIST function
  role  (internal|private|public) "public"
  name  CDATA #REQUIRED
>
<!ELEMENT proto (#PCDATA)>  
<!ELEMENT code  (#PCDATA)>  
<!ATTLIST code  
  role (header|code) "code"
>
<!ELEMENT constants (constant)*>
<!ELEMENT constant (#PCDATA)>
<!ATTLIST constant
  name  CDATA #REQUIRED
  value CDATA #REQUIRED
  type  (string|int|float) "string"
>

<!ELEMENT globals (phpini|global)*>
<!ELEMENT phpini (#PCDATA)>
<!ATTLIST phpini
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  value CDATA #REQUIRED
  access (system|perdir|user|all) "all"
  onupdate CDATA #IMPLIED
>
<!ELEMENT global (#PCDATA)>
<!ATTLIST global
  name CDATA #REQUIRED
  type CDATA #REQUIRED
>

<!ELEMENT deps (with|lib|header|file|program)*>
<!ATTLIST deps
  language (c|cpp) "c"
  platform   (unix|win32|all) "all"
>
<!ELEMENT with (#PCDATA)>
<!ATTLIST with
  defaults CDATA #REQUIRED
  testfile CDATA #REQUIRED
  name     CDATA #IMPLIED
>
<!ELEMENT lib (#PCDATA)>
<!ATTLIST lib
  name       CDATA #REQUIRED
  function   CDATA #REQUIRED
  searchpath CDATA #IMPLIED
  platform   (unix|win32|all) "all"
>
<!ELEMENT header (#PCDATA)>
<!ATTLIST header
  name       CDATA #REQUIRED
  function   CDATA #IMPLIED
  searchpath CDATA #IMPLIED
  prepend  (yes|no) "no"
>

<!ELEMENT resources (resource)*>
<!ELEMENT resource (description?, destruct?)>
<!ATTLIST resource
  name       CDATA #REQUIRED
  payload    CDATA #IMPLIED
	alloc      (yes|no) "no"
>
<!ELEMENT destruct (#PCDATA)>

<!ELEMENT streams (stream)*>
<!ELEMENT stream (description?, ops?, data?)>
<!ATTLIST stream
  name CDATA #REQUIRED
>
<!ELEMENT ops (op)*>
<!ELEMENT op (#PCDATA)>
<!ATTLIST op
  name CDATA #REQUIRED
>


<!ELEMENT tests (test)*>
<!ELEMENT test (title, skipif?, post?, get?, code, output)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT skipif (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT get (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT output (#PCDATA)>

=== ifeghali/php-src/scripts/ext_skel_ng/extension.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE extension SYSTEM "extension.dtd">
<extension>
	<name>dummy</name>
  <summary>experimental dummy extension</summary>
  <description>
   this is used for testing of the extension generater only
  </description>
	
  <maintainers>
		<maintainer>		
			<user>hholzgra</user>
			<name>Hartmut Holzgraefe</name>
			<email>hholzgra@php.net</email>
			<role>lead</role>
		</maintainer>
		<maintainer>		
			<user>dummy</user>
			<name>Crashtest Dummy</name>
			<email>dummy@example.com</email>
			<role>dummy</role>
		</maintainer>
  </maintainers>
		
	<logo src='dummy.gif'></logo>

  <release>
		<version>0.1</version>
		<date>2002-02-16</date>
		<state>alpha</state>
    <license>php</license>
    <notes>
      - first experimental draft
    </notes>
  </release>

  <changelog>
  </changelog>
	

	<deps language="c">
	  <!-- these are not yet used in any way :( -->
    <with defaults='/usr:/usr/local' testfile='include/dummy.h'></with>
    <lib name='dummy' function='dummy' searchpath='/usr/lib:/lib'></lib>
  </deps>

  <constants>
		<constant name="DUMMY_OK"  type="int" value="1">dummy ok status</constant>
		<constant name="DUMMY_ERR" type="int" value="0">dummy fault status</constant>
  </constants>

  <globals>
		<global name="foobar"     type="int"></global>
		<phpini name="foo_int"    type="int"    value="42"     access="system">some int value</phpini> 
		<phpini name="foo_bool"   type="int"    value="on"     access="all"   onupdate="OnUpdateBool"></phpini> 
		<phpini name="foo_string" type="string" value="foobar" access="all"   ></phpini> 
  </globals>

  <resources>
		<resource name="dummy_resource" payload="char *">
			<description>
        a dummy string resource
      </description>
			<destruct>
<![CDATA[
  free(resource);
]]>
      </destruct>
		</resource>
		<resource name="dummy_resource2">
		</resource>
	</resources>


  <functions>
		
    <function role='internal' name='MINIT'>
      <code>
<![CDATA[
  int dummy = 42;

  dummy = dummy;
]]>
      </code>
    </function>

    <function role='internal' name='MSHUTDOWN'>
      <code>
<![CDATA[
  int dummy = 42;

  dummy = dummy;
]]>
      </code>
    </function>

    <function role='internal' name='RINIT'>
      <code>
<![CDATA[
  int dummy = 42;

  dummy = dummy;
]]>
      </code>
    </function>

    <function role='internal' name='RSHUTDOWN'>
      <code>
<![CDATA[
  int dummy = 42;

  dummy = dummy;
]]>
      </code>
    </function>

    <function role='internal' name='MINFO'>
      <code>
<![CDATA[
  php_info_print_table_start();
  php_info_print_table_header(2, "test", "table");
  php_info_print_table_end();
]]>
      </code>
    </function>

		<function role='private' name='myfunc'>
      <code>
<![CDATA[
  static int myfunc(void) { 
    return 23;
  }
]]>
      </code>
    </function>


		<function role='public' name='dummy_int'>
			<summary>dummy integer conversion</summary>
			<proto>int dummy_int(int bar)</proto>
			<description>
some funcy longer description

foo
bar
		  </description>
		</function>

		<function role='public' name='dummy_resource'>
			<summary>dummy resource test</summary>
			<proto>resource dummy_resource(resource bar)</proto>
		</function>
		
		<function name='dummy_string'>
			<summary>dummy string conversion</summary>
			<proto>string dummy_string(string bar) foobar</proto>
			<code>
<![CDATA[
  RETURN_STRINGL(bar, bar_len, 1);
]]>
      </code>
		</function>
		
		<function name ="dummy_void">
			<proto>void dummy_void(void)</proto>
		</function>

		<function name ="dummy_void2">
			<proto>void dummy_void2()</proto>
		</function>

  </functions>
	
</extension>
